# Generated by Django 5.0.4 on 2024-05-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='institute',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
