# Generated by Django 5.0.4 on 2024-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_institute_doctor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
