# Generated by Django 4.2.13 on 2024-05-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_verified_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='friday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='friday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='monday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='monday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='saturday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='saturday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='sunday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='sunday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='thursday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='thursday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='tuesday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='tuesday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='wednesday_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='wednesday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_image'),
        ),
    ]
