# Generated by Django 4.2.13 on 2024-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctoravailability_friday_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BO', 'Booked'), ('CO', 'Consulted'), ('CA', 'Canceled')], default='BO', max_length=2),
        ),
    ]
