# Generated by Django 4.2.13 on 2024-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('consulted', 'Consulted'), ('canceled', 'Canceled')], default='booked', max_length=10),
        ),
    ]
