# Generated by Django 4.2.13 on 2024-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_speciality_remove_doctor_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
